### ISSUE TITLE
🚢Release 0.6.0

### ISSUE THREAD

**Issue by jperl** [qawolf/qawolf#212]
- [x] 💪Revamp selector #189
- [x] 🦊Setup "qawolf gitlab" #193
- [x] 🏷️Deploy tags to docker #207
- [x] Update examples https://github.com/qawolf/nytimes-example/commit/4340ab4dcab7852751f5d3bae869daee9972e970 https://github.com/qawolf/theinternet-example/commit/b3d78baa5e9cede14f6d7b61e2ed229e909b3095 https://github.com/qawolf/united-example/commit/9ad4d9ab3e6b4ab8fdcc7483125fc24aa0f62192
- [x] 🏷️Use fixed version in `qawolf [ci]` templates #210
- [x] ✏️Inline values in test to make editing easier #191
- [x] 🐛currentPage should not choose a closed page #213

**Comment by jperl** [comment]
Released will update docs separately
