### ISSUE TITLE
🚢v0.8.0 checklist

### ISSUE THREAD

**Issue by jperl** [qawolf/qawolf#306]
- [x] Release alpha.0
- [x] Test `npm i -g qawolf` works properly with alias #283 
- [x] Fix and add test for process.exit(1) on jest failure
- [x] Run unit tests on node v10 & node v12
- [x] Fix QAWolfBrowser page default for current page
- [x] Fix `qawolf test` for windows 
- [x] Run unit tests on windows with CI
- [x] Fix cache for circle ci / gitlab / etc
- [x] Alias record -> create so it is backwards compatible (with log explaining it is deprecated and will be removed in v1)
- [x] Release alpha.1
- [x] Update all example repos
- [x] Update CI templates (cache node_modules)
- [x] Add mocha example #281 
- [x] Release 0.8.0
- [x] Deploy docs

~~Do we need`@qawolf/disable-chrome-security-warning` [script](https://github.com/qawolf/qawolf/blob/v0.7.11/Dockerfile#L23-L26) to disable "Chrome is being controlled by automated test software"~~

**Comment by jperl** [comment]
- [ ] Fix and add test for page staying on current page
- [ ] Fix and add test for process.exit(1) on jest failure

**Comment by jperl** [comment]
Mocha example https://github.com/qawolf/united-example/commit/6d8199689914295cbeb82183b0326c0dd8600ff1
